### ISSUE TITLE
Getting error while using drand mainnet

### ISSUE THREAD

**Issue by alvosec** [drand/tlock#35]
If I try to use drand mainnet while using tle.go it will respond as follow:

`go run tle.go -n="http://api.drand.sh/" -c="8990e7a9aaed2ffed73dbd7092123d6f289930540d7651336225dc172e51b2ce" -D=5s -o=encrypted_data plain`

```
bash does not belong to an unchained network
exit status 1
```

How can we switch from testnet to mainnet and get full functionality of tle?

**Comment by CluEleSsUK** [comment]
Hi Alvosec, timelock relies on unchained randomness to work correctly. Currently mainnet is only a chained network but we plan on creating a new unchained network in mainnet in mid December.
We will likely publish a blog post announcing when we do!

**Comment by gruberdev** [comment]
> Hi Alvosec, timelock relies on unchained randomness to work correctly. Currently mainnet is only a chained network but we plan on creating a new unchained network in mainnet in mid December. We will likely publish a blog post announcing when we do!

Until that goes in effect, if I were to encrypt a file for 30 days on the unstable network, how unreliable are we talking? Is the reliability of the API endpoints the only difference on the chain status? I have recently learned of this project and I see multiple uses for it, thank you for your work on it, +1.

**Comment by CluEleSsUK** [comment]
The main difference is that there are a lower number of participants in testnet - that means theoretically a lower number of institutions need to be compromised to reach a threshold number of nodes (and thus decrypt everything).
There is also the chance that we reset testnet or break it, but so far this hasn’t happened!

From a reliability point of view, the testnet has had the same uptime as mainnet as far as I know.

Great to hear you’re building on top of tlock though - would love to hear more about your projects and help you where we can (we have a slack channel if you want to have more extended chats).
