### ISSUE TITLE
tlock-go: 3 dependencies have vulnerabilities

### ISSUE THREAD

**Issue by CluEleSsUK** [drand/tlock#46]

**Comment by CluEleSsUK** [comment]
Have looked into this - all are transitive dependencies from `drand/drand`. Curiously, tlock pulls in the _whole_ of drand rather than just the client, and running `go get github.com/drand/drand/client` seems to do this.
Updating the downstream dependency on `quic-go` requires an update to a libp2p lib, which I've raised a PR for [here](https://github.com/libp2p/go-nat/pull/27)

**Comment by CluEleSsUK** [comment]
actually quic-go has already been upgraded in newer versions of drand. I've raised a PR to update tlock-go deps here: https://github.com/drand/tlock/pull/58

**Comment by AnomalRoil** [comment]
fixed in #58
