### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by yCobanoglu** [drand/tlock#83]
Hi i get this error on trying to decrypt my file:
```
creating client: doing request: Get "https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/info": context deadline exceeded
```
command i am using "tle  --decrypt encrypted_file2"

**Comment by CluEleSsUK** [comment]
does it happen consistently or intermittently? 
Does it happen with `api2.drand.sh`?
We had some reports of context timeouts for folk in Australia because of latency, though it might be unrelated

**Comment by yCobanoglu** [comment]
okay it worked with "api2.drand.sh" thanks. I am located in Germany.
